apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:26.4.7
        args:
          - start
        env:
          - name: KC_DB
            value: mysql
          - name: KC_DB_URL
            value: jdbc:mysql://keycloak-mysql.auth.svc.cluster.local:3306/keycloak
          - name: KC_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: keycloak-db-secret
                key: MYSQL_USER
          - name: KC_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-db-secret
                key: MYSQL_PASSWORD

          - name: KC_BOOTSTRAP_ADMIN_USERNAME
            value: admin
          - name: KC_BOOTSTRAP_ADMIN_PASSWORD
            value: admin

          - name: KC_HTTP_ENABLED
            value: "true"
          - name: KC_PROXY
            value: edge
          - name: KC_PROXY_HEADERS
            value: xforwarded

          - name: KC_HOSTNAME
            value: keycloak.local
          - name: KC_HOSTNAME_STRICT
            value: "false"
          - name: KC_HOSTNAME_STRICT_HTTPS
            value: "false"

        ports:
          - containerPort: 8080

