version: 1.0

provider:
  name: openfaas
  gateway: http://127.0.0.1:31112

functions:

  confidential-function:
    lang: python3-http
    handler: ./functions/confidential
    image: pawanarora/confidential-function:0.1.2
    annotations:
      ifc/label: "confidential"

  internal-function:
    lang: python3-http
    handler: ./functions/internal
    image: pawanarora/internal-function:0.1.2
    annotations:
      ifc/label: "internal"

  public-function:
    lang: python3-http
    handler: ./functions/public
    image: pawanarora/public-function:0.1.2
    annotations:
      ifc/label: "public"
